Merged Updates from BLFS/LFS SVNs

diff --git a/clfs/init.d/functions b/clfs/init.d/functions
--- a/clfs/init.d/functions
+++ b/clfs/init.d/functions
@@ -50,12 +50,23 @@ fi
 COL=$((${COLUMNS} - 8))
 WCOL=$((${COL} - 2))
 
-## Set Cursor Position Commands, used via echo -e
+## Provide an echo that supports -e and -n
+# If formatting is needed, $ECHO should be used
+case "`echo -e -n test`" in
+	-[en]*)
+		ECHO=/bin/echo
+		;;
+	*)
+		ECHO=echo
+		;;
+esac
+
+## Set Cursor Position Commands, used via $ECHO
 SET_COL="\\033[${COL}G"      # at the $COL char
 SET_WCOL="\\033[${WCOL}G"    # at the $WCOL char
 CURS_UP="\\033[1A\\033[0G"   # Up one line, at the 0'th char
 
-## Set color commands, used via echo -e
+## Set color commands, used via $ECHO
 # Please consult `man console_codes for more information
 # under the "ECMA-48 Set Graphics Rendition" section
 #
@@ -114,15 +125,11 @@ boot_mesg()
 	done
 
 	## Figure out the length of what is to be printed to be used
-        ## for warning messges. 
-	STRING_LENGTH="`echo "${1}" | sed \
-		-e 's,.,.,g' -e 'l 1' | grep -c \$`"
+	## for warning messages. 
+	STRING_LENGTH=$((${#1} + 1))
 
 	# Print the message to the screen
-	echo ${ECHOPARM} -e "${2}${1}"
-	if [ "$LOGGING" ]; then
-		DISPLAYLOG="${1}"
-	fi
+	${ECHO} ${ECHOPARM} -e "${2}${1}"
 	
 }
 
@@ -146,9 +153,6 @@ boot_log()
 
 echo_ok()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${SUCCESS}  OK  ${BRACKET}]"
-	echo -e "${NORMAL}"
-	boot_mesg_flush "[  OK  ]"
 	if [ "$LCD_PROG" ]; then
 		if [ "$LCD_LINES" = "2" ]; then
 			LCD_OUT2="[  OK  ]"
@@ -156,15 +160,15 @@ echo_ok()
 		else
 			LCD_OUT2="${LCD_OUT1:0:12} OK"
 			$LCD_PROG "$LCD_OUT2" > /dev/null 2>&1
-		fi			
+		fi
 	fi
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${SUCCESS}  OK  ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
+	boot_mesg_flush
 }
 
 echo_failure()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${FAILURE} FAIL ${BRACKET}]"
-	echo -e "${NORMAL}"
-	boot_mesg_flush "[ FAIL ]"
 	if [ "$LCD_PROG" ]; then
 		if [ "$LCD_LINES" = "2" ]; then
 			LCD_OUT2="[ FAIL  ]"
@@ -174,12 +178,13 @@ echo_failure()
 			$LCD_PROG "$LCD_OUT2" > /dev/null 2>&1
 		fi
 	fi
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${FAILURE} FAIL ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
+	boot_mesg_flush
 }
 
 echo_warning()
 {
-	echo -n -e "${CURS_UP}${SET_COL}${BRACKET}[${WARNING} WARN ${BRACKET}]"
-	echo -e "${NORMAL}"
 	if [ "$LCD_PROG" ]; then
 		if [ "$LCD_LINES" = "2" ]; then
 			LCD_OUT2="[ WARN  ]"
@@ -187,9 +192,11 @@ echo_warning()
 		else
 			LCD_OUT2="${LCD_OUT1:0:10} WARN"
 			$LCD_PROG "$LCD_OUT2" > /dev/null 2>&1
-		fi			
+		fi
 	fi
-	boot_mesg_flush "[ WARN ]"
+	${ECHO} -n -e "${CURS_UP}${SET_COL}${BRACKET}[${WARNING} WARN ${BRACKET}]"
+	${ECHO} -e "${NORMAL}"
+	boot_mesg_flush
 }
 
 print_error_msg()
@@ -197,7 +204,6 @@ print_error_msg()
 	echo_failure
 	# $i is inherited by the rc script
 	boot_log "\n\n${i} failed and exited with a return value of ${error_value}."
-	boot_mesg_flush
 	boot_mesg -n "FAILURE:\n\nYou should not be reading this error message.\n\n" ${FAILURE}
 	boot_mesg -n " It means that an unforeseen error took"
 	boot_mesg -n " place in ${i}, which exited with a return value of"
@@ -208,15 +214,9 @@ print_error_msg()
 	boot_mesg -n " the CLFS book, please be so kind to inform us at"
 	boot_mesg " clfs-dev@cross-lfs.org.\n"
 	boot_mesg_flush
-	if [ "$INTERACTIVE" ]; then
-		boot_mesg -n "Press Enter to continue..." ${INFO}
-		boot_mesg "" ${NORMAL}
-		if [ "$LCD_PROG" ]; then
-			sleep 10
-		else
-			read ENTER
-		fi
-	fi
+	boot_mesg -n "Press Enter to continue..." ${INFO}
+	boot_mesg "" ${NORMAL}
+	read ENTER
 }
 
 check_script_status()
@@ -257,9 +257,6 @@ print_status()
 		return 1
 	fi
 
-#	boot_mesg_flush
-#	echo_warning
-
 	case "${1}" in
 
 		success)
@@ -271,20 +268,20 @@ print_status()
 			# may call it this way.
 			case "${2}" in
 				running)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Already running." ${WARNING}
 					echo_warning
 					;;
 				not_running)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Not running." ${WARNING}
 					echo_warning
 					;;
 				not_available)
-					echo -e -n "${CURS_UP}"
-					echo -e -n "\\033[${STRING_LENGTH}G   "
+					${ECHO} -e -n "${CURS_UP}"
+					${ECHO} -e -n "\\033[${STRING_LENGTH}G   "
 					boot_mesg "Not available." ${WARNING}
 					echo_warning
 					;;
@@ -306,15 +303,44 @@ print_status()
 
 reloadproc()
 {
-	if [ "${#}" = "0" ]; then
-		echo "Usage: reloadproc [{program}]"
-		exit 1
+	local pidfile=""
+	local failure=0
+
+	while true
+	do
+		case "${1}" in
+			-p)
+				pidfile="${2}"
+				shift 2
+				;;
+			-*)
+				log_failure_msg "Unknown Option: ${1}"
+				return 2
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+
+	if [ "${#}" -lt "1" ]; then
+		log_failure_msg "Usage: reloadproc [-p pidfile] pathname"
+		return 2
 	fi
 
-	getpids "${1}"
+	# This will ensure compatibility with previous CLFS Bootscripts
+	if [ -n "${PIDFILE}" ];	then
+		pidfile="${PIDFILE}"
+	fi
+
+	# Is the process running?
+	if [ -z "${pidfile}" ];	then
+		pidofproc -s "${1}"
+	else
+		pidofproc -s -p "${pidfile}" "${1}"
+	fi
 
 	if [ -n "${pidlist}" ];	then
-		failure="0"
 		for pid in ${pidlist}
 		do
 			kill -"${RELOADSIG}" "${pid}" || failure="1"
@@ -331,30 +357,70 @@ reloadproc()
 
 statusproc()
 {
-	if [ "${#}" = "0" ]
-	then
-		echo "Usage: statusproc {program}"
-		exit 1
+	local pidfile=""
+	local base=""
+	local ret=""
+
+	while true
+	do
+		case "${1}" in
+			-p)
+				pidfile="${2}"
+				shift 2
+				;;
+			-*)
+				log_failure_msg "Unknown Option: ${1}"
+				return 2
+				;;
+			*)
+				break
+				;;
+		esac
+	done
+
+	if [ "${#}" != "1" ]; then
+		shift 1
+		log_failure_msg "Usage: statusproc [-p pidfile] pathname"
+		return 2
 	fi
 
-	getpids "${1}"
+	# Get the process basename
+	base="${1##*/}"
+
+	# This will ensure compatibility with previous CLFS Bootscripts
+	if [ -n "${PIDFILE}" ];	then
+		pidfile="${PIDFILE}"
+	fi
+
+	# Is the process running?
+	if [ -z "${pidfile}" ];	then
+		pidofproc -s "${1}"
+	else
+		pidofproc -s -p "${pidfile}" "${1}"
+	fi
+
+	# Store the return status
+	ret=$?
 
 	if [ -n "${pidlist}" ];	then
-		echo -e "${INFO}${base} is running with Process"\
+		${ECHO} -e "${INFO}${base} is running with Process"\
 			"ID(s) ${pidlist}.${NORMAL}"
 	else
 		if [ -n "${base}" -a -e "/var/run/${base}.pid" ]; then
-			echo -e "${WARNING}${1} is not running but"\
+			${ECHO} -e "${WARNING}${1} is not running but"\
 				"/var/run/${base}.pid exists.${NORMAL}"
 		else
-			if [ -n "${PIDFILE}" -a -e "${PIDFILE}" ]; then
-				echo -e "${WARNING}${1} is not running"\
-					"but ${PIDFILE} exists.${NORMAL}"
+			if [ -n "${pidfile}" -a -e "${pidfile}" ]; then
+				${ECHO} -e "${WARNING}${1} is not running"\
+					"but ${pidfile} exists.${NORMAL}"
 			else
-				echo -e "${INFO}${1} is not running.${NORMAL}"
+				${ECHO} -e "${INFO}${1} is not running.${NORMAL}"
 			fi
 		fi
 	fi
+
+	# Return the status from pidofproc
+	return $ret
 }
 
 # The below functions are documented in the LSB-generic 2.1.0
@@ -425,11 +491,11 @@ pidofproc()
 		for pid in ${lpids}
 		do
 			if [ "${pid}" -ne "$$" -a "${pid}" -ne "${PPID}" ]; then
-				kill -0 "${pid}" > /dev/null &&
+				kill -0 "${pid}" 2>/dev/null &&
 				pidlist="${pidlist} ${pid}"
 			fi
 			
-			if [ "${silent}" -ne "1" ]; then
+			if [ "${silent}" != "1" ]; then
 				echo "${pidlist}"
 			fi
 
@@ -442,7 +508,7 @@ pidofproc()
 
 	else
 		pidlist=`pidof -o $$ -o $PPID -x "$1"`
-		if [ "x${silent}" != "x1" ]; then
+		if [ "${silent}" != "1" ]; then
 			echo "${pidlist}"
 		fi
 
@@ -591,10 +657,10 @@ loadproc()
 killproc()
 {
 	local pidfile=""
-	local killsig=""
+	local killsig=TERM # default signal is SIGTERM
 	pidlist=""
 
-# This will ensure compatibility with previous CLFS Bootscripts
+	# This will ensure compatibility with previous CLFS Bootscripts
 	if [ -n "${PIDFILE}" ];	then
 		pidfile="${PIDFILE}"
 	fi
@@ -609,7 +675,7 @@ killproc()
 			-*)
 				log_failure_msg "Unknown Option: ${1}"
 				return 2
-			;;
+				;;
 			*)
  				break
 				;;
@@ -624,37 +690,49 @@ killproc()
 		return 2
 	fi
 
+	# Is the process running?
 	if [ -z "${pidfile}" ];	then
 		pidofproc -s "${1}"
 	else
 		pidofproc -s -p "${pidfile}" "${1}"
 	fi
 
-    # Change....
+    # If running, send the signal
     if [ -n "${pidlist}" ]; then
 	for pid in ${pidlist}
 	do
-		kill -${killsig:-TERM} ${pid} 2>/dev/null
-		if [ -z "${killsig}" ]; then
-			# Wait up to 3 seconds, for ${pid} to terminate
-			local dtime=${KILLDELAY}
+		kill -${killsig} ${pid} 2>/dev/null
+
+		# Wait up to 3 seconds, for ${pid} to terminate
+		case "${killsig}" in
+		TERM|SIGTERM|KILL|SIGKILL)
+			# sleep in 1/10ths of seconds and
+			# multiply KILLDELAY by 10
+			local dtime="${KILLDELAY}0"
 			while [ "${dtime}" != "0" ]
 			do
 				kill -0 ${pid} 2>/dev/null || break
-				sleep 1
+				sleep 0.1
 				dtime=$(( ${dtime} - 1))
 			done
 			# If ${pid} is still running, kill it
 			kill -0 ${pid} 2>/dev/null && kill -KILL ${pid} 2>/dev/null
-		fi
+			;;
+		esac
 	done
 
-	if [ -z "${killsig}" ];	then
-		pidofproc -s "${1}"
+	# Check if the process is still running if we tried to stop it
+	case "${killsig}" in
+	TERM|SIGTERM|KILL|SIGKILL)
+		if [ -z "${pidfile}" ];	then
+			pidofproc -s "${1}"
+		else
+			pidofproc -s -p "${pidfile}" "${1}"
+		fi
 
 		# Program was terminated
 		if [ "$?" != "0" ]; then
-			# Pidfile Exists
+			# Remove the pidfile if necessary
 			if [ -f "${pidfile}" ];	then
 				rm -f "${pidfile}"
 			fi
@@ -664,17 +742,13 @@ killproc()
 			echo_failure
 			return 4 # Unknown Status
 		fi
-	else
-		if [ -z "${pidfile}" ];	then
-			pidofproc -s "${1}"
-		else
-			pidofproc -s -p "${pidfile}" "${1}"
-		fi
-	fi
-
-	evaluate_retval # This is "Probably" not LSB compliant, but required to be compatible with older bootscripts
-
-    else
+		;;
+	*)
+		# Just see if the kill returned successfully
+		evaluate_retval
+		;;
+	esac
+    else # process not running
 	print_status warning not_running
     fi
 }
@@ -696,8 +770,8 @@ killproc()
 #*******************************************************************************
 log_success_msg()
 {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${SUCCESS}""  OK  ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${SUCCESS}""  OK  ""${BRACKET}""]""${NORMAL}"
 	return 0
 }
 
@@ -716,8 +790,8 @@ log_success_msg()
 #
 #*******************************************************************************
 log_failure_msg() {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${FAILURE}"" FAIL ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${FAILURE}"" FAIL ""${BRACKET}""]""${NORMAL}"
 	return 0
 }
 
@@ -736,8 +810,8 @@ log_failure_msg() {
 #
 #*******************************************************************************
 log_warning_msg() {
-	echo -n -e "${BOOTMESG_PREFIX}${@}"
-	echo -e "${SET_COL}""${BRACKET}""[""${WARNING}"" WARN ""${BRACKET}""]""${NORMAL}"
+	${ECHO} -n -e "${BOOTMESG_PREFIX}${@}"
+	${ECHO} -e "${SET_COL}""${BRACKET}""[""${WARNING}"" WARN ""${BRACKET}""]""${NORMAL}"
 	return 0
 }
 
diff --git a/clfs/init.d/modules b/clfs/init.d/modules
--- a/clfs/init.d/modules
+++ b/clfs/init.d/modules
@@ -21,67 +21,47 @@
 case "${1}" in
 	start)
 
-		# If proc is mounted, find the current kernel
-		# message level 
-		if [ -f /proc/sys/kernel/printk ]; then
-			prev_msg=`cat /proc/sys/kernel/printk | \
-					sed 'l 1' | sed -n '2~0p' | \
-					sed 's/\\\//'`
-		else 
-			prev_msg="6"
-		fi
+		# Exit if there's no modules file or there are no
+		# valid entries
+		[ -r /etc/sysconfig/modules ] &&
+			egrep -qv '^($|#)' /etc/sysconfig/modules ||
+			exit 0
 
-		# Now set the message level to 1 so not to make too 
-		# much noise when loading modules
-		dmesg -n 1
+		boot_mesg -n "Loading modules:" ${INFO}
 
 		# Only try to load modules if the user has actually given us
 		# some modules to load.
-		if egrep -qv '^(#|$)' /etc/sysconfig/modules 2>/dev/null
-		then
+		while read module args; do
 
-			# Read in the configuration file.
-			exec 9>&0 < /etc/sysconfig/modules
+			# Ignore comments and blank lines.
+			case "$module" in
+				""|"#"*) continue ;;
+			esac
 
-				boot_mesg -n "Loading modules:" ${INFO}
+			# Attempt to load the module, making
+			# sure to pass any arguments provided.
+			modprobe ${module} ${args} >/dev/null
 
-				while read module args
-				do
-					# Ignore comments and blank lines.
-					case "${module}" in
-						""|\#*) continue ;;
-					esac
+			# Print the module name if successful,
+			# otherwise take note.
+			if [ $? -eq 0 ]; then
+				boot_mesg -n " ${module}" ${NORMAL}
+			else
+				failedmod="${failedmod} ${module}"
+			fi
+		done < /etc/sysconfig/modules
 
-					# Attempt to load the module, making
-					# sure to pass any arguments provided.
-					modprobe ${module} ${args} 2>&1 > /dev/null
+		boot_mesg "" ${NORMAL}
+		# Print a message about successfully loaded
+		# modules on the correct line.
+		echo_ok
 
-					# Print the module name if successful,
-					# otherwise take note.
-					if [ ${?} -eq 0 ]; then
-						boot_mesg -n " ${module}" ${NORMAL}
-					else
-						failedmod="${failedmod} ${module}"
-					fi
-				done
-
-				boot_mesg "" ${NORMAL}
-				# Print a message about successfully loaded
-				# modules on the correct line.
-				echo_ok
-
-				# Print a failure message with a list of any
-				# modules that may have failed to load.
-				if [ "${failedmod}" ]; then
-					boot_mesg "Failed to load modules:${failedmod}" ${FAILURE}
-					echo_failure
-				fi
-
-			exec 0>&9 9>&-
-
+		# Print a failure message with a list of any
+		# modules that may have failed to load.
+		if [ -n "${failedmod}" ]; then
+			boot_mesg "Failed to load modules:${failedmod}" ${FAILURE}
+			echo_failure
 		fi
-		# Set the kernel message level back to it's previous value.
-		dmesg -n "${prev_msg}"
 		;;
 	*)
 		echo "Usage: ${0} {start}"
